"""Report persistence — text output with header formatting and optional JSON export."""

import json
import logging
import re
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)

_DEFAULT_OUTPUT_DIR = Path("reports")
_SEPARATOR = "=" * 62


def save_report(
    report: str,
    features: dict,
    output_dir: Path = _DEFAULT_OUTPUT_DIR,
    json_export: bool = False,
) -> Path:
    """Write a generated report to disk with a structured header.

    Args:
        report: Narrative text returned by the LLM.
        features: Feature dictionary produced by features.extract_features().
        output_dir: Directory to write into (created automatically if absent).
        json_export: When True, also writes a JSON file alongside the text report.

    Returns:
        Path to the saved text file.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    stem = _safe_stem(features["force"], features["period"])
    txt_path = output_dir / f"{stem}.txt"

    txt_path.write_text(_format_report(report, features), encoding="utf-8")
    logger.info("Text report saved: %s", txt_path)

    if json_export:
        json_path = output_dir / f"{stem}.json"
        _write_json(json_path, report, features)
        logger.info("JSON export saved: %s", json_path)

    return txt_path


# ── Private helpers ───────────────────────────────────────────────────────────

def _format_report(report: str, features: dict) -> str:
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    mom_line = ""
    mom = features.get("mom_change")
    if mom and mom.get("absolute") is not None:
        sign = "+" if mom["absolute"] > 0 else ""
        mom_line = (
            f"  MoM Change : {mom['direction'].title()} "
            f"{sign}{mom['absolute']:,} ({mom['pct']}%)\n"
        )

    header = (
        f"{_SEPARATOR}\n"
        f"  CRIME BRIEFING REPORT\n"
        f"  Force      : {features['force']}\n"
        f"  Period     : {features['period']}\n"
        f"  Total      : {features['total_crimes']:,} crimes\n"
        f"{mom_line}"
        f"  Generated  : {generated_at}\n"
        f"{_SEPARATOR}\n"
    )

    footer = (
        f"\n{_SEPARATOR}\n"
        f"  Generated by AI Crime Report Generator\n"
        f"  Verify all figures against source data before publication.\n"
        f"{_SEPARATOR}\n"
    )

    return header + "\n" + report.strip() + footer


def _write_json(path: Path, report: str, features: dict) -> None:
    payload: dict = {
        "metadata": {
            "force": features["force"],
            "period": features["period"],
            "total_crimes": features["total_crimes"],
            "generated_at": datetime.now().isoformat(),
        },
        "source_statistics": {
            "top_categories": features["top_categories"],
            "distribution": features["distribution"],
        },
        "report": report.strip(),
    }
    if "mom_change" in features:
        payload["source_statistics"]["mom_change"] = features["mom_change"]

    path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def _safe_stem(force: str, period: str) -> str:
    """Produce a safe filesystem stem from force name and period."""
    safe_force = re.sub(r"[^\w\s-]", "", force).strip().replace(" ", "_")
    safe_period = re.sub(r"[^\w-]", "", period)
    return f"{safe_force}_{safe_period}"
